print("Welcome to Miku Concert Experience!")
print("Here you can pretend you touch grass on a daily basis and have money to go to concerts!")
print("You can virtually see Miku!")
print("Yay!")
print("Let's start with your name: ")
name = input()
print("Have fun, " +name+ ".")

print("You find yourself at a Miku concert!")
print("The crowd is cheering, lightsticks waving in every direction. You see Miku walking past you.")
print("What do you say to Hatsune Miku?")
answer = input()
print("You said: " +answer+ ".")
print("Miku says hi and that she is sorry she cannot talk longer and that she has to perform a concert!")
print("Do you want to watch the Hatsune Miku concert? (yes or no only)")
yesno = input()
print("You said " +yesno+ "")
if yesno == "yes" or "Yes":
        print("You go to the Miku concert! Miku sings 'The Miku Song.'")
elif yesno == "no" or "No":
        print("You attempt to leave the Miku concert but Miku's singing makes you want to stay. You realize that Miku is so great!")
        print("Miku sings 'The Miku Song.'")
print("What do you cheer in the crowd?")
cheer = input()
print("You cheered: " +cheer+ "!")
print("Miku waves at you! Do you:")
print("(A or B) A: Scream 'I LOVE YOU MIKU!' or B: Ignore her.")
AorB = input()
if AorB == "A" or "a":
    print("You tell Miku that you love her! Miku does BTS finger hearts for you!")
    print("You tear up as your idol has finally recognized you!")
    print("Your vision goes blurry and then... darkness.")
    print("...")
    print("It's the next morning. Birds whistle outside. Sun streams through the windows. You open your eyes...")
    print("Only to find you are in the hospital! After you fainted, you must have been trampled by Miku's other fans.")
    print("You gasp as you see Miku standing above you.")
    print("You say, 'No worries, it's not a big deal,' as you fight back a grimace of pain.")
    print("Miku does BTS finger hearts to you. You feel your heart thumping out of your chest.")
    print("" +name+ ", Miku says.")
    print("'Before...' you start. 'Before I die... I mean, get discharged, can you sing me a song?")
    print("Miku smiles! 'Okay,' she says. She sings the Miku song.")
    print("Miku's voice fills your ears and you smile, reaching for her hand...")
    print("Miku holds out her hand. Do you reach out to take it? (yes or no)")
    mikuhand = input()
    if mikuhand == "yes" or "Yes":
        print("You reach for Miku's hand.")
        print("Miku smiles. You bring your hand to hers...")
        print("...but your hand goes right through hers!! Your smile falters as Miku flickers.")
        print("'Miku?!' you ask frantically. Miku smiles and does BTS finger hearts to you.")
        print("You realize... Miku is just a hologram.")
        print("You stare at the empty room where Miku once stood, the white tile turning grey before your eyes, the world becoming sadder each passing second.")
        print("You fall asleep... you will forever miss Miku.")
    if mikuhand == "no" or "No":
        print("You pull your hand back. You cannot be friends with Miku. It would never work.")
        print("Miku is sad. And then...")
        print("MIKU RAGE MODE ACTIVATED.")
        print("Miku attempts to punch you! You slide out of the way, but your movement is limited in your hospital bed.")
        print("Miku's second punch lands right on your stomach! You growl in rage, punching her back!")
        print("Miku gasps in RAGE and summons a light stick sword, jumping at you!")
        print("You summon a hammer, and jump at Miku with equal power.")
        print("Miku yells, 'It's me or you, " +name+ "! Give up now!'")
        print("'Never!' You yell, dodging Miku. You smash your hammer on Miku and she goes flying!")
        print("You gasp in shock, realizing what you've done.")
        print("Miku never talks to you again.")
    if AorB == "B" or "b":
        print("Miku notices you ignored her! She looks sad, but then...")
        print("SHE SINGS YOU THE ENTIRE MIKU SONG IN REVENGE!")
        print("But it's too long to write, BUT SHE DOES SING IT!")
        print("After the show, Miku sues you for making her sad! You lose all your money.")
        print("GAME OVER.")